Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -82,7 +82,7 @@ jobs:
           cp ../../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./common/ || true
           cp ../../kernel_patches/next/syscall_hooks.patch ./common/ || true
           cp ../../susfs4ksu/kernel_patches/fs/* ./common/fs/ || true
-          cp ../../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/ || true
+          cp ../../susfs4ksu/include/linux/susfs.h ./common/include/linux/ || true
           if [[ "${{ env.ENABLE_LZ4KD }}" == "true" ]]; then
             cp ../../kernel_patches/001-lz4.patch ./common/ || true
             cp ../../kernel_patches/lz4armv8.S ./common/lib || true
@@ -97,6 +97,8 @@ jobs:
             git apply -p1 < 001-lz4.patch || true
             patch -p1 < 002-zstd.patch || true
           fi
+          # Debug: List susfs.h to confirm copy
+          ls -l ./include/linux/susfs.h || echo "susfs.h not found"
 
       - name: Add SUSFS config
         run: |
